# resolver: ghc-7.10.3
# resolver: nightly-2016-04-14
resolver: lts-6.25  # for ghc 7.10.3
# resolver: lts-7.16 # GHC 8.0.1

packages:
  - '.'

extra-deps:
  - servant-0.6.1
  - servant-client-0.6.1
  - servant-server-0.6.1
  - logging-effect-1.2.0